// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace msg {

namespace {

const ::google::protobuf::Descriptor* msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  msg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_2eproto() {
  protobuf_AddDesc_msg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg.proto");
  GOOGLE_CHECK(file != NULL);
  msg_descriptor_ = file->message_type(0);
  static const int msg_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, arg1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, arg2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, arg3_),
  };
  msg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      msg_descriptor_,
      msg::default_instance_,
      msg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(msg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    msg_descriptor_, &msg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_2eproto() {
  delete msg::default_instance_;
  delete msg_reflection_;
}

void protobuf_AddDesc_msg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tmsg.proto\022\003msg\"I\n\003msg\022\014\n\004name\030\001 \002(\t\022\n\n"
    "\002id\030\002 \002(\005\022\014\n\004arg1\030\003 \002(\t\022\014\n\004arg2\030\004 \001(\t\022\014\n"
    "\004arg3\030\005 \001(\t", 91);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg.proto", &protobuf_RegisterTypes);
  msg::default_instance_ = new msg();
  msg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_2eproto {
  StaticDescriptorInitializer_msg_2eproto() {
    protobuf_AddDesc_msg_2eproto();
  }
} static_descriptor_initializer_msg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int msg::kNameFieldNumber;
const int msg::kIdFieldNumber;
const int msg::kArg1FieldNumber;
const int msg::kArg2FieldNumber;
const int msg::kArg3FieldNumber;
#endif  // !_MSC_VER

msg::msg()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:msg.msg)
}

void msg::InitAsDefaultInstance() {
}

msg::msg(const msg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:msg.msg)
}

void msg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  arg1_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg2_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  arg3_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

msg::~msg() {
  // @@protoc_insertion_point(destructor:msg.msg)
  SharedDtor();
}

void msg::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (arg1_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete arg1_;
  }
  if (arg2_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete arg2_;
  }
  if (arg3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete arg3_;
  }
  if (this != default_instance_) {
  }
}

void msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return msg_descriptor_;
}

const msg& msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2eproto();
  return *default_instance_;
}

msg* msg::default_instance_ = NULL;

msg* msg::New() const {
  return new msg;
}

void msg::Clear() {
  if (_has_bits_[0 / 32] & 31) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    id_ = 0;
    if (has_arg1()) {
      if (arg1_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        arg1_->clear();
      }
    }
    if (has_arg2()) {
      if (arg2_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        arg2_->clear();
      }
    }
    if (has_arg3()) {
      if (arg3_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        arg3_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:msg.msg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_id;
        break;
      }

      // required int32 id = 2;
      case 2: {
        if (tag == 16) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_arg1;
        break;
      }

      // required string arg1 = 3;
      case 3: {
        if (tag == 26) {
         parse_arg1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->arg1().data(), this->arg1().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "arg1");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_arg2;
        break;
      }

      // optional string arg2 = 4;
      case 4: {
        if (tag == 34) {
         parse_arg2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->arg2().data(), this->arg2().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "arg2");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_arg3;
        break;
      }

      // optional string arg3 = 5;
      case 5: {
        if (tag == 42) {
         parse_arg3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_arg3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->arg3().data(), this->arg3().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "arg3");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:msg.msg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:msg.msg)
  return false;
#undef DO_
}

void msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:msg.msg)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required int32 id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // required string arg1 = 3;
  if (has_arg1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->arg1().data(), this->arg1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "arg1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->arg1(), output);
  }

  // optional string arg2 = 4;
  if (has_arg2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->arg2().data(), this->arg2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "arg2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->arg2(), output);
  }

  // optional string arg3 = 5;
  if (has_arg3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->arg3().data(), this->arg3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "arg3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->arg3(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:msg.msg)
}

::google::protobuf::uint8* msg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.msg)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required int32 id = 2;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // required string arg1 = 3;
  if (has_arg1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->arg1().data(), this->arg1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "arg1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->arg1(), target);
  }

  // optional string arg2 = 4;
  if (has_arg2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->arg2().data(), this->arg2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "arg2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->arg2(), target);
  }

  // optional string arg3 = 5;
  if (has_arg3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->arg3().data(), this->arg3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "arg3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->arg3(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.msg)
  return target;
}

int msg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required int32 id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string arg1 = 3;
    if (has_arg1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->arg1());
    }

    // optional string arg2 = 4;
    if (has_arg2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->arg2());
    }

    // optional string arg3 = 5;
    if (has_arg3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->arg3());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void msg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const msg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const msg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void msg::MergeFrom(const msg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_arg1()) {
      set_arg1(from.arg1());
    }
    if (from.has_arg2()) {
      set_arg2(from.arg2());
    }
    if (from.has_arg3()) {
      set_arg3(from.arg3());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void msg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msg::CopyFrom(const msg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void msg::Swap(msg* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(id_, other->id_);
    std::swap(arg1_, other->arg1_);
    std::swap(arg2_, other->arg2_);
    std::swap(arg3_, other->arg3_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = msg_descriptor_;
  metadata.reflection = msg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)
